name: How to use environment variables
on:
  workflow_dispatch:
env:
  ENV_WORKFLOW: "VALOR WORKFLOW"
jobs:  
  test-env:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "VALOR JOB test-env"
    steps:  
      - name: Run job
        env:
          ENV_ACTION: "VALOR ACTION Run job"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"
      - name: Run second job
        env:
          ENV_ACTION: "VALOR ACTION Run second job"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"

  test-env-2:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "VALOR JOB test-env-2"
    steps:  
      - name: Run job 2
        env:
          ENV_ACTION: "VALOR ACTION Run job 2"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"
      - name: Run second job 2
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
